version: '3.2'

services:

    redis:
      image: "redis:alpine"
      command: redis-server #--requirepass passwd1234
      ports:
        - "6379:6379"
      volumes:
        - ./volume/redis-data:/var/lib/redis
        - ./volume/redis.conf:/usr/local/etc/redis/redis.conf
      environment:
        - REDIS_REPLICATION_MODE=master

#Redis web UI
    rebrow:
      image: "marian/rebrow"
      ports:
        - "5001:5001"
      links:
        - "redis:myredis"