CREATE TYPE optype AS ENUM('INSERT', 'UPDATE', 'DELETE');

CREATE TYPE prntType AS ENUM('MOTHER', 'FATHER', 'GRANDFATHER', 'GRANDMOTHER', 'GUARDIAN', 'OTHER');

CREATE TYPE genderType AS ENUM('MALE', 'FEMALE');