CREATE DATABASE IF NOT EXISTS cinema_booking_system;
USE cinema_booking_system;

CREATE TABLE IF NOT EXISTS rooms (

	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(45) NOT NULL,
	no_seats INT NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;