CREATE DATABASE IF NOT EXISTS school ;
use school ;

CREATE TABLE IF NOT EXISTS pupils (
    firstname VARCHAR(25) NOT NULL,
    lastname VARCHAR(25) NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(70),
    joined DATE NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET=utf8
PARTITION BY RANGE(YEAR(joined)) (
    PARTITION p0 VALUES LESS THAN (1960),
    PARTITION p1 VALUES LESS THAN (1970),
    PARTITION p2 VALUES LESS THAN (1980),
    PARTITION p3 VALUES LESS THAN (1990),
    PARTITION p4 VALUES LESS THAN MAXVALUE
);


insert into pupils (firstname, lastname, username, email, joined) values ('Gert', 'Bilbrook',            CONCAT(firstname, '-', lastname),              'gbilbrook0@nature.com',                                                   STR_TO_DATE('02/16/1955',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Jamil', 'Vonasek',            CONCAT(firstname, '-', lastname),              'jvonasek1@howstuffworks.com',                                                   STR_TO_DATE('06/04/2004',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Nevsa', 'Esberger',           CONCAT(firstname, '-', lastname),               'nesberger2@bluehost.com',                                                   STR_TO_DATE('08/06/2008',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Rorke', 'Valentinuzzi',       CONCAT(firstname, '-', lastname),              'rvalentinuzzi3@google.com.au',                                                   STR_TO_DATE('10/24/1965',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Augie', 'Defew',              CONCAT(firstname, '-', lastname),              'adefew4@blinklist.com',                                                   STR_TO_DATE('09/26/2002',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Shanta', 'Penkethman',        CONCAT(firstname, '-', lastname),               'spenkethman5@mediafire.com',                                                   STR_TO_DATE('12/07/2010',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Cesare', 'Shelsher',          CONCAT(firstname, '-', lastname),              'cshelsher6@umich.edu',                                                   STR_TO_DATE('02/15/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Dimitri', 'Borles',           CONCAT(firstname, '-', lastname),              'dborles7@hp.com',                                                   STR_TO_DATE('05/12/2004',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Ab', 'Grinsted',              CONCAT(firstname, '-', lastname),              'agrinsted8@nationalgeographic.com',                                                   STR_TO_DATE('06/04/2006',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Hernando', 'Bisp',            CONCAT(firstname, '-', lastname),              'hbisp9@mlb.com',                                                   STR_TO_DATE('07/18/2004',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Stearne', 'Monument',         CONCAT(firstname, '-', lastname),                'smonumenta@craigslist.org',                                                   STR_TO_DATE('02/27/2012',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Artemis', 'Morriss',          CONCAT(firstname, '-', lastname),               'amorrissb@scientificamerican.com',                                                   STR_TO_DATE('10/01/2005',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Rodolphe', 'Pantin',          CONCAT(firstname, '-', lastname),              'rpantinc@answers.com',                                                   STR_TO_DATE('06/16/1955',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Mortie', 'Hartless',          CONCAT(firstname, '-', lastname),               'mhartlessd@tinypic.com',                                                   STR_TO_DATE('02/28/1965',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Yuri', 'Borrows',             CONCAT(firstname, '-', lastname),               'yborrowse@illinois.edu',                                                   STR_TO_DATE('04/18/2003',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Owen', 'Fidilis',             CONCAT(firstname, '-', lastname),                'ofidilisf@sfgate.com',                                                   STR_TO_DATE('06/20/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Chance', 'Allix',             CONCAT(firstname, '-', lastname),               'callixg@tripod.com',                                                   STR_TO_DATE('12/22/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Beitris', 'Guymer',           CONCAT(firstname, '-', lastname),             'bguymerh@hugedomains.com',                                                   STR_TO_DATE('11/14/2003',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Rozalin', 'Gobert',           CONCAT(firstname, '-', lastname),              'rgoberti@howstuffworks.com',                                                   STR_TO_DATE('11/30/2009',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Donavon', 'Lovick',           CONCAT(firstname, '-', lastname),             'dlovickj@ovh.net',                                                   STR_TO_DATE('07/10/1955',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Juline', 'Case',              CONCAT(firstname, '-', lastname),           'jcasek@statcounter.com',                                                   STR_TO_DATE('03/17/2005',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Ber', 'Spata',                CONCAT(firstname, '-', lastname),               'bspatal@usa.gov',                                                   STR_TO_DATE('06/07/2004',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Had', 'Wintersgill',          CONCAT(firstname, '-', lastname),               'hwintersgillm@comsenz.com',                                                   STR_TO_DATE('07/01/2011',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Ivory', 'Tidmas',             CONCAT(firstname, '-', lastname),            'itidmasn@nationalgeographic.com',                                                   STR_TO_DATE('06/15/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Max', 'Birchenhead',          CONCAT(firstname, '-', lastname),               'mbirchenheado@ning.com',                                                   STR_TO_DATE('01/16/2006',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Roderich', 'Litel',           CONCAT(firstname, '-', lastname),              'rlitelp@mail.ru',                                                   STR_TO_DATE('03/03/2006',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Mehetabel', 'Lyte',           CONCAT(firstname, '-', lastname),              'mlyteq@seesaa.net',                                                   STR_TO_DATE('05/05/2011',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Louie', 'Tunnow',             CONCAT(firstname, '-', lastname),            'ltunnowr@google.fr',                                                   STR_TO_DATE('06/26/2011',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Adore', 'Annion',             CONCAT(firstname, '-', lastname),                  'aannions@netscape.com',                                                   STR_TO_DATE('06/11/2012',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Baillie', 'Casaro',           CONCAT(firstname, '-', lastname),              'bcasarot@bbb.org',                                                   STR_TO_DATE('09/15/2004',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Elias', 'Speaks',             CONCAT(firstname, '-', lastname),                  'espeaksu@mit.edu',                                                   STR_TO_DATE('10/08/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Brande', 'Schoenfisch',       CONCAT(firstname, '-', lastname),            'bschoenfischv@trellian.com',                                                   STR_TO_DATE('11/29/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Abramo', 'Curmi',             CONCAT(firstname, '-', lastname),            'acurmiw@unicef.org',                                                   STR_TO_DATE('05/24/2011',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Tracey', 'Joseph',            CONCAT(firstname, '-', lastname),             'tjosephx@hp.com',                                                   STR_TO_DATE('06/24/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Derwin', 'Marder',            CONCAT(firstname, '-', lastname),             'dmardery@skype.com',                                                   STR_TO_DATE('02/05/2007',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Budd', 'Fumagalli',           CONCAT(firstname, '-', lastname),              'bfumagalliz@cyberchimps.com',                                                   STR_TO_DATE('05/22/2002',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Annie', 'Mazella',            CONCAT(firstname, '-', lastname),             'amazella10@omniture.com',                                                   STR_TO_DATE('08/11/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Mareah', 'Darlington',        CONCAT(firstname, '-', lastname),                 'mdarlington11@mapy.cz',                                                   STR_TO_DATE('11/19/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Bevon', 'Eilles',             CONCAT(firstname, '-', lastname),            'beilles12@bandcamp.com',                                                   STR_TO_DATE('10/01/2005',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Dukey', 'Camilleri',          CONCAT(firstname, '-', lastname),               'dcamilleri13@tmall.com',                                                   STR_TO_DATE('11/05/1965',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Randell', 'Waldron',          CONCAT(firstname, '-', lastname),               'rwaldron14@ameblo.jp',                                                   STR_TO_DATE('04/02/2010',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Garik', 'Annesley',           CONCAT(firstname, '-', lastname),              'gannesley15@w3.org',                                                   STR_TO_DATE('04/17/2012',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Kristin', 'Bessant',          CONCAT(firstname, '-', lastname),                           'kbessant16@narod.ru',                                                   STR_TO_DATE('11/01/2006',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Dodi', 'Creegan',             CONCAT(firstname, '-', lastname),                        'dcreegan17@squarespace.com',                                                   STR_TO_DATE('04/12/2007',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Aurthur', 'Skurm',            CONCAT(firstname, '-', lastname),             'askurm18@baidu.com',                                                   STR_TO_DATE('06/28/2007',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Christophe', 'Tansley',       CONCAT(firstname, '-', lastname),                   'ctansley19@ebay.com',                                                   STR_TO_DATE('11/22/2005',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Bartolomeo', 'Brotherheed',   CONCAT(firstname, '-', lastname),                       'bbrotherheed1a@is.gd',                                                   STR_TO_DATE('06/17/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Zulema', 'Rugieri',           CONCAT(firstname, '-', lastname),               'zrugieri1b@epa.gov',                                                   STR_TO_DATE('06/02/2011',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Codie', 'Ive',                CONCAT(firstname, '-', lastname),              'cive1c@wikispaces.com',                                                   STR_TO_DATE('01/20/2007',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Caddric', 'Scrivens',         CONCAT(firstname, '-', lastname),                 'cscrivens1d@un.org',                                                   STR_TO_DATE('01/21/2009',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Byram', 'Filon',              CONCAT(firstname, '-', lastname),            'bfilon1e@creativecommons.org',                                                   STR_TO_DATE('02/27/2006',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Estevan', 'Leyshon',          CONCAT(firstname, '-', lastname),                'eleyshon1f@howstuffworks.com',                                                   STR_TO_DATE('01/06/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Cyril', 'Belson',             CONCAT(firstname, '-', lastname),             'cbelson1g@bloglines.com',                                                   STR_TO_DATE('06/26/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Frederica', 'Missington',     CONCAT(firstname, '-', lastname),                     'fmissington1h@tamu.edu',                                                   STR_TO_DATE('05/21/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Rosita', 'Divine',            CONCAT(firstname, '-', lastname),              'rdivine1i@abc.net.au',                                                   STR_TO_DATE('11/07/1955',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Rabi', 'Crudge',              CONCAT(firstname, '-', lastname),            'rcrudge1j@ca.gov',                                                   STR_TO_DATE('05/30/2007',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Georgena', 'Graves',          CONCAT(firstname, '-', lastname),                'ggraves1k@smh.com.au',                                                   STR_TO_DATE('12/25/2004',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Vladimir', 'Orrum',           CONCAT(firstname, '-', lastname),               'vorrum1l@abc.net.au',                                                   STR_TO_DATE('03/16/1955',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Kelby', 'Blasl',              CONCAT(firstname, '-', lastname),            'kblasl1m@ibm.com',                                                   STR_TO_DATE('09/03/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Dodie', 'Gadd',               CONCAT(firstname, '-', lastname),           'dgadd1n@whitehouse.gov',                                                   STR_TO_DATE('10/04/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Anestassia', 'Conkling',      CONCAT(firstname, '-', lastname),                    'aconkling1o@eventbrite.com',                                                   STR_TO_DATE('05/25/2003',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Lawton', 'Dalzell',           CONCAT(firstname, '-', lastname),               'ldalzell1p@bbb.org',                                                   STR_TO_DATE('03/08/2008',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Kym', 'Cowp',                 CONCAT(firstname, '-', lastname),                      'kcowp1q@whitehouse.gov',                                                   STR_TO_DATE('07/04/2003',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Sharia', 'Roberti',           CONCAT(firstname, '-', lastname),               'sroberti1r@slashdot.org',                                                   STR_TO_DATE('02/08/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Heinrick', 'Caunter',         CONCAT(firstname, '-', lastname),                  'hcaunter1s@elpais.com',                                                   STR_TO_DATE('11/24/2002',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Hunter', 'Chappelow',         CONCAT(firstname, '-', lastname),                  'hchappelow1t@unicef.org',                                                   STR_TO_DATE('09/19/1965',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Clarke', 'Poveleye',          CONCAT(firstname, '-', lastname),                 'cpoveleye1u@mozilla.org',                                                   STR_TO_DATE('08/12/1965',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Eleanore', 'Sears',           CONCAT(firstname, '-', lastname),                 'esears1v@wsj.com',                                                   STR_TO_DATE('07/31/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Jeramey', 'Ravens',           CONCAT(firstname, '-', lastname),                 'jravens1w@dailymail.co.uk',                                                   STR_TO_DATE('10/26/2007',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Kelvin', 'Arndtsen',          CONCAT(firstname, '-', lastname),                 'karndtsen1x@pen.io',                                                   STR_TO_DATE('11/24/2011',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Gena', 'Tankard',             CONCAT(firstname, '-', lastname),               'gtankard1y@linkedin.com',                                                   STR_TO_DATE('01/18/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Teddi', 'Martell',            CONCAT(firstname, '-', lastname),               'tmartell1z@alibaba.com',                                                   STR_TO_DATE('03/25/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Piper', 'Delves',             CONCAT(firstname, '-', lastname),               'pdelves20@prweb.com',                                                   STR_TO_DATE('02/05/2010',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Lea', 'Matthiae',             CONCAT(firstname, '-', lastname),               'lmatthiae21@sitemeter.com',                                                   STR_TO_DATE('12/07/2007',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Helli', 'Mardee',             CONCAT(firstname, '-', lastname),               'hmardee22@princeton.edu',                                                   STR_TO_DATE('02/11/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Nancee', 'Haysom',            CONCAT(firstname, '-', lastname),               'nhaysom23@wsj.com',                                                   STR_TO_DATE('11/20/2006',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Hershel', 'Howlett',          CONCAT(firstname, '-', lastname),                 'hhowlett24@istockphoto.com',                                                   STR_TO_DATE('06/15/2009',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Mina', 'Adanet',              CONCAT(firstname, '-', lastname),             'madanet25@webnode.com',                                                   STR_TO_DATE('06/25/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Dar', 'Alesbrook',            CONCAT(firstname, '-', lastname),               'dalesbrook26@sina.com.cn',                                                   STR_TO_DATE('07/20/2011',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Octavia', 'Venmore',          CONCAT(firstname, '-', lastname),                 'ovenmore27@yolasite.com',                                                   STR_TO_DATE('08/21/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Brynna', 'Delgado',           CONCAT(firstname, '-', lastname),                'bdelgado28@posterous.com',                                                   STR_TO_DATE('08/06/2009',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Mia', 'Tatters',              CONCAT(firstname, '-', lastname),             'mtatters29@nba.com',                                                   STR_TO_DATE('08/31/2010',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Cherilynn', 'Kuschek',        CONCAT(firstname, '-', lastname),                   'ckuschek2a@shinystat.com',                                                   STR_TO_DATE('09/04/1965',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Isabelle', 'Biever',          CONCAT(firstname, '-', lastname),                 'ibiever2b@tinypic.com',                                                   STR_TO_DATE('07/22/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Basia', 'Giacomini',          CONCAT(firstname, '-', lastname),                 'bgiacomini2c@amazonaws.com',                                                   STR_TO_DATE('04/29/1955',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Sherman', 'Pawel',            CONCAT(firstname, '-', lastname),               'spawel2d@weebly.com',                                                   STR_TO_DATE('08/06/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Arlee', 'Geggie',             CONCAT(firstname, '-', lastname),              'ageggie2e@mac.com',                                                   STR_TO_DATE('05/20/2002',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Rozamond', 'Caze',            CONCAT(firstname, '-', lastname),               'rcaze2f@europa.eu',                                                   STR_TO_DATE('03/28/2008',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Angy', 'Faulds',              CONCAT(firstname, '-', lastname),             'afaulds2g@pinterest.com',                                                   STR_TO_DATE('07/08/2002',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Austina', 'Stead',            CONCAT(firstname, '-', lastname),               'astead2h@washingtonpost.com',                                                   STR_TO_DATE('07/24/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Elijah', 'Josovich',          CONCAT(firstname, '-', lastname),                 'ejosovich2i@google.cn',                                                   STR_TO_DATE('06/15/2004',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Fredric', 'Winterborne',      CONCAT(firstname, '-', lastname),                     'fwinterborne2j@globo.com',                                                   STR_TO_DATE('09/12/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Cleopatra', 'Nisby',          CONCAT(firstname, '-', lastname),                 'cnisby2k@angelfire.com',                                                   STR_TO_DATE('03/14/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Erick', 'O''Hoolahan',        CONCAT(firstname, '-', lastname),                   'eohoolahan2l@cnet.com',                                                   STR_TO_DATE('07/11/2008',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Frazer', 'Ximenez',           CONCAT(firstname, '-', lastname),                'fximenez2m@timesonline.co.uk',                                                   STR_TO_DATE('03/18/2006',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Wallie', 'MacKnight',         CONCAT(firstname, '-', lastname),                  'wmacknight2n@jugem.jp',                                                   STR_TO_DATE('01/20/2004',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Erick', 'Edling',             CONCAT(firstname, '-', lastname),              'eedling2o@yellowpages.com',                                                   STR_TO_DATE('12/11/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Flor', 'Benedito',            CONCAT(firstname, '-', lastname),               'fbenedito2p@sogou.com',                                                   STR_TO_DATE('09/21/2009',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ('Katherina', 'Biglin',         CONCAT(firstname, '-', lastname),                  'kbiglin2q@wsj.com',                                                   STR_TO_DATE('08/01/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Gwendolen', 'Fann',          CONCAT(firstname, '-', lastname),                 'gfann2r@psu.edu',                                                   STR_TO_DATE('05/12/2008',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Hogan', 'Lamburn',           CONCAT(firstname, '-', lastname),                'hlamburn2s@qq.com',                                                   STR_TO_DATE('02/20/2003',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Torr', 'Douthwaite',         CONCAT(firstname, '-', lastname),                  'tdouthwaite2t@mashable.com',                                                   STR_TO_DATE('09/20/2003',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Devi', 'Godrich',            CONCAT(firstname, '-', lastname),               'dgodrich2u@springer.com',                                                   STR_TO_DATE('06/16/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Jody', 'Djurevic',           CONCAT(firstname, '-', lastname),                'jdjurevic2v@ibm.com',                                                   STR_TO_DATE('03/31/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Robby', 'Haye',              CONCAT(firstname, '-', lastname),             'rhaye2w@alibaba.com',                                                   STR_TO_DATE('01/01/2005',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Pen', 'Willavoys',           CONCAT(firstname, '-', lastname),                'pwillavoys2x@moonfruit.com',                                                   STR_TO_DATE('04/01/1965',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Bertram', 'Sibille',         CONCAT(firstname, '-', lastname),                  'bsibille2y@phpbb.com',                                                   STR_TO_DATE('06/08/2009',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Catie', 'Westcott',          CONCAT(firstname, '-', lastname),                 'cwestcott2z@reverbnation.com',                                                   STR_TO_DATE('09/23/2003',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Frayda', 'Dike',             CONCAT(firstname, '-', lastname),              'fdike30@bloglovin.com',                                                   STR_TO_DATE('10/22/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Roxanna', 'Foro',            CONCAT(firstname, '-', lastname),               'rforo31@intel.com',                                                   STR_TO_DATE('01/01/2003',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Lock', 'Boodell',            CONCAT(firstname, '-', lastname),               'lboodell32@examiner.com',                                                   STR_TO_DATE('01/07/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Tomasina', 'Hickenbottom',   CONCAT(firstname, '-', lastname),              'thickenbottom33@usda.gov',                                                   STR_TO_DATE('12/06/2010',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Tiffy', 'Leaburn',           CONCAT(firstname, '-', lastname),                'tleaburn34@imageshack.us',                                                   STR_TO_DATE('05/30/2003',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Dare', 'Goldhill',           CONCAT(firstname, '-', lastname),                'dgoldhill35@sun.com',                                                   STR_TO_DATE('07/03/2009',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Aurilia', 'Deneve',          CONCAT(firstname, '-', lastname),                 'adeneve36@skyrock.com',                                                   STR_TO_DATE('05/12/2008',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Guthrie', 'Myrtle',          CONCAT(firstname, '-', lastname),                 'gmyrtle37@webeden.co.uk',                                                   STR_TO_DATE('04/06/2004',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Vaclav', 'Corzor',           CONCAT(firstname, '-', lastname),                'vcorzor38@sun.com',                                                   STR_TO_DATE('05/08/2006',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Dita', 'Biaggioni',          CONCAT(firstname, '-', lastname),                 'dbiaggioni39@blogger.com',                                                   STR_TO_DATE('03/02/2009',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Brannon', 'Hullett',         CONCAT(firstname, '-', lastname),                  'bhullett3a@vinaora.com',                                                   STR_TO_DATE('12/29/2008',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Dwight', 'Lillee',           CONCAT(firstname, '-', lastname),                'dlillee3b@amazon.co.jp',                                                   STR_TO_DATE('02/27/2010',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Collete', 'Facchini',        CONCAT(firstname, '-', lastname),                   'cfacchini3c@independent.co.uk',                                                   STR_TO_DATE('11/02/2002',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Morry', 'Jakeway',           CONCAT(firstname, '-', lastname),                'mjakeway3d@mozilla.com',                                                   STR_TO_DATE('11/09/2012',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Farrel', 'Kilborn',          CONCAT(firstname, '-', lastname),                 'fkilborn3e@zimbio.com',                                                   STR_TO_DATE('02/17/1965',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Dorian', 'Aguilar',          CONCAT(firstname, '-', lastname),                 'daguilar3f@ucla.edu',                                                   STR_TO_DATE('03/24/2005',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Rob', 'Wherry',              CONCAT(firstname, '-', lastname),             'rwherry3g@360.cn',                                                   STR_TO_DATE('07/11/2012',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Beverie', 'Pideon',          CONCAT(firstname, '-', lastname),                 'bpideon3h@pcworld.com',                                                   STR_TO_DATE('03/21/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Jorry', 'McDougal',          CONCAT(firstname, '-', lastname),                 'jmcdougal3i@github.io',                                                   STR_TO_DATE('07/28/2008',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Robinson', 'Brendel',        CONCAT(firstname, '-', lastname),                   'rbrendel3j@51.la',                                                   STR_TO_DATE('09/01/1965',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Iorgos', 'Rowet',            CONCAT(firstname, '-', lastname),               'irowet3k@msu.edu',                                                   STR_TO_DATE('12/01/2008',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Lotte', 'Sante',             CONCAT(firstname, '-', lastname),              'lsante3l@bbb.org',                                                   STR_TO_DATE('04/10/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Jeno', 'St Leger',           CONCAT(firstname, '-', lastname),                'jstleger3m@si.edu',                                                   STR_TO_DATE('09/29/2008',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Darbee', 'Whitehall',        CONCAT(firstname, '-', lastname),                   'dwhitehall3n@about.com',                                                   STR_TO_DATE('07/08/1985',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Hulda', 'Jerzycowski',       CONCAT(firstname, '-', lastname),                    'hjerzycowski3o@usatoday.com',                                                   STR_TO_DATE('11/21/2006',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Arvin', 'Leinster',          CONCAT(firstname, '-', lastname),                 'aleinster3p@cafepress.com',                                                   STR_TO_DATE('08/21/2008',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Gino', 'Givens',             CONCAT(firstname, '-', lastname),              'ggivens3q@mlb.com',                                                   STR_TO_DATE('10/17/1955',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Zeb', 'Monketon',            CONCAT(firstname, '-', lastname),               'zmonketon3r@edublogs.org',                                                   STR_TO_DATE('01/14/2011',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Inger', 'Boatright',         CONCAT(firstname, '-', lastname),                  'iboatright3s@vk.com',                                                   STR_TO_DATE('11/29/2008',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Torrance', 'Braithwaite',    CONCAT(firstname, '-', lastname),                       'tbraithwaite3t@cbslocal.com',                                                   STR_TO_DATE('05/26/1975',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Alisun', 'Grono',            CONCAT(firstname, '-', lastname),               'agrono3u@thetimes.co.uk',                                                   STR_TO_DATE('01/04/2009',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Jolyn', 'Kyberd',            CONCAT(firstname, '-', lastname),               'jkyberd3v@weebly.com',                                                   STR_TO_DATE('03/09/2010',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Camellia', 'Cogman',         CONCAT(firstname, '-', lastname),                  'ccogman3w@amazonaws.com',                                                   STR_TO_DATE('05/24/1965',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Bronny', 'Cuff',             CONCAT(firstname, '-', lastname),              'bcuff3x@desdev.cn',                                                   STR_TO_DATE('12/08/2005',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Philipa', 'Mardoll',         CONCAT(firstname, '-', lastname),                  'pmardoll3y@sbwire.com',                                                   STR_TO_DATE('11/02/2002',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Nydia', 'Kiljan',            CONCAT(firstname, '-', lastname),               'nkiljan3z@shareasale.com',                                                   STR_TO_DATE('01/12/2011',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Gunner', 'Maykin',           CONCAT(firstname, '-', lastname),                'gmaykin40@nih.gov',                                                   STR_TO_DATE('07/27/2007',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Hayyim', 'Ganniclifft',      CONCAT(firstname, '-', lastname),                     'hganniclifft41@shinystat.com',                                                   STR_TO_DATE('02/04/2009',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Charley', 'Hinrichsen',      CONCAT(firstname, '-', lastname),                     'chinrichsen42@squidoo.com',                                                   STR_TO_DATE('06/05/1955',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Reuben', 'Bubeer',           CONCAT(firstname, '-', lastname),                'rbubeer43@free.fr',                                                   STR_TO_DATE('11/22/2012',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Stacey', 'Galero',           CONCAT(firstname, '-', lastname),                'sgalero44@bluehost.com',                                                   STR_TO_DATE('11/03/2011',  '%m/%d/%Y'));
insert into pupils (firstname, lastname, username, email, joined) values ( 'Melany', 'Wakeling',         CONCAT(firstname, '-', lastname),                  'mwakeling45@telegraph.co.uk',                                                   STR_TO_DATE('09/07/2008',  '%m/%d/%Y'));
