DROP TABLE IF EXISTS classes;
CREATE TABLE IF NOT EXISTS classes (
    id SERIAL PRIMARY KEY NOT NULL,
	type VARCHAR(12),
	class_head_id INTEGER,
	name VARCHAR(5),


	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	created_by varchar(50) DEFAULT CURRENT_USER,
	modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, --ON UPDATE CURRENT_TIMESTAMP,
 	modified_by varchar(50) DEFAULT CURRENT_USER

)
