DROP TABLE IF EXISTS marks;
CREATE TABLE IF NOT EXISTS marks (
    id SERIAL PRIMARY KEY NOT NULL,
	subject_id INTEGER,
	pupil_id INTEGER,
	date DATE,
	value INTEGER,

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	created_by varchar(50) DEFAULT CURRENT_USER,
	modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, --ON UPDATE CURRENT_TIMESTAMP,
 	modified_by varchar(50) DEFAULT CURRENT_USER

)