DROP TABLE IF EXISTS subjects;
CREATE TABLE IF NOT EXISTS subjects (
    id SERIAL PRIMARY KEY NOT NULL,
	teacher_id INTEGER,
	name VARCHAR(10),


	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	created_by varchar(50) DEFAULT CURRENT_USER,
	modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, --ON UPDATE CURRENT_TIMESTAMP,
 	modified_by varchar(50) DEFAULT CURRENT_USER

)
