version: '3.1'

services:
  db:
    container_name: "postgres"
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=school
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres-dump:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"