version: '3'

services:
  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    hostname: mongodb
    command: mongod --port 27027
    volumes:
      - ./volumes/dumps:/backup
    restart: always
    expose:
      - "22"
    ports:
      - "27027:27027"