version: '3'

services:
  oracle:
    image: truevoly/oracle-12c
    container_name: oracle
    environment:
      - ORACLE_PWD=admin
    ports:
      - "1521:1521"
      - "8080:8080"
    volumes:
      - $PWD/data/oracle/oradata:/opt/oracle/oradata
      - $PWD/data/oracle/oradata/recovery_area:/opt/oracle/oradata/recovery_area
      - $PWD/data/oracle/ora-setup-scripts:/opt/oracle/scripts/setup
      - $PWD/data/oracle/ora-startup-scripts:/opt/oracle/scripts/startup
      - $PWD/db-leach:/opt/oracle/product/12.2.0.1/dbhome_1/

#  adminer:
#    build: .
#    restart: always
#    ports:
#      - "8081:8080"