version: '3'

services:
  db:
    container_name: "mysql"
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=school
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ./volumes/mysql-dump:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8091:8080"